### ISSUE TITLE
php8.0 and above

### ISSUE THREAD

**Issue by vingin007** [php-casbin/hyperf-permission#2]
Hello,

I've been trying to use the yi17310320725/hyperf-permission package in my project, but I noticed that it requires PHP ^7.2 and doesn't currently support PHP 8.1, which I am using.

I wanted to reach out and ask if there are any plans to update the package to support PHP 8.0 and above in the near future?

Thank you for your time and consideration.

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
Hi , @vingin007 
Just now, v1.0.0 was released, the package name is changed to: `casbin/hyperf-permission`, supports `php8`, you can try it.

**Comment by vingin007** [comment]
Thank you so much. It would be perfect if you could relax the version constraints for hyperf/config.

**Comment by leeqvip** [comment]
@vingin007 Are you familiar with the `hyperf` framework? Looking forward to your PR submission if possible.

**Comment by vingin007** [comment]
Not really, still getting familiar with it.

**Comment by hsluoyz** [comment]
@vingin007 this file, isn't it? What version do you want to relax to?

https://github.com/php-casbin/hyperf-permission/blob/0493e42542d914d69b1ab098fbede3d99101cb56/composer.json#L19
